apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1  # Adjust replicas as needed
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: docker.io/hazemfelhi/client:v1
          imagePullPolicy: "IfNotPresent"  # Replace with your Django Docker image name and tag
          ports:
            - containerPort: 9003  # Adjust port as per your Django app configuration
          env:
            - name: POSTGRES_DB
              value: devdb  # Replace with your PostgreSQL database name
            - name: POSTGRES_USER
              value: devuser  # Replace with your PostgreSQL username
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_HOST
              value: postgresql  # Replace with your PostgreSQL service name in Kubernetes
            - name: POSTGRES_PORT
              value: "5432"  # Adjust if your PostgreSQL uses a different port

