apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HazemFelhi/k8s.git
    targetRevision: HEAD
    path: postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: papello
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HazemFelhi/k8s.git'
    targetRevision: HEAD
    path: front
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: papello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HazemFelhi/k8s.git'
    targetRevision: HEAD
    path: User
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: papello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HazemFelhi/k8s.git'
    targetRevision: HEAD
    path: core
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: papello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/HazemFelhi/k8s.git'
    targetRevision: HEAD
    path: client
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: papello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true