apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: git@github.com:username/repo.git
      sshPrivateKeySecret:
        name: argocd-repo-private-key
        key: ssh-privatekey
