apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1  # Adjust replicas as needed
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          #image: docker.io/hazemfelhi/papello_ia_back:vc
          #image: docker.io/hazemfelhi/client_back:vc
          #image : docker.io/hazemfelhi/backend-ingresss:vc
          #image : docker.io/hazemfelhi/papello-new-back:vc
          #image: docker.io/hazemfelhi/final-back
          #image: docker.io/hazemfelhi/back-client:vc3
          #image: docker.io/hazemfelhi/back-clientt:vc4
          image: docker.io/hazemfelhi/back-end
          command: ["python"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]
          imagePullPolicy: "IfNotPresent"  # Replace with your Django Docker image name and tag
          ports:
            - containerPort: 8000  # Adjust port as per your Django app configuration
          volumeMounts:
            - name: media-volume
              mountPath: /app/media
          envFrom:
          - secretRef:
              name: aws-credentials
          env:
            - name: POSTGRES_DB
              value: appdb  # Replace with your PostgreSQL database name
            - name: POSTGRES_USER
              value: devuser  # Replace with your PostgreSQL username
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_HOST
              value: postgresql  # Replace with your PostgreSQL service name in Kubernetes
            - name: POSTGRES_PORT
              value: "5432"  # Adjust if your PostgreSQL uses a different port
            - name: REDIS_HOST
              value: redis  # Ensure this matches your Redis service name
            - name: REDIS_PORT
              value: "6379"
      volumes:
          - name: media-volume
            persistentVolumeClaim:
              claimName: media-pvc