apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVRDS0FNMlpGQlFBVkhGR0s=
  AWS_SECRET_ACCESS_KEY: SG9VMXFSYjZFODRSREZ2OFB5aDJsbE5hR1E4RHJtd2hWVWk4bG1TRQ==
