apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  labels:
    app: front
    tier: front
spec:
  selector: # postgresql Pod Should contain same labels
    matchLabels:
      app: front
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: front
        tier: front
    spec:
      containers:
        - name: front
          #image: docker.io/hazemfelhi/front_papello_client:vc
          #image: docker.io/hazemfelhi/papello_client_front:vc1
          #image: docker.io/hazemfelhi/papello_ia_front:vc
          #image: docker.io/hazemfelhi/client_front:vc
          image: docker.io/hazemfelhi/frontend-ingress
          ports:
              - containerPort: 9000