apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-back-ingress
  namespace: papello  # Specify the namespace here if needed
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Specify the Ingress class name
  rules:
  - hosts: a1c698ea2ea3849d8a9ff29fce9d10b1-1999298649.us-east-1.elb.amazonaws.com
    http:
      paths:
      - path: /papello
        pathType: Prefix
        backend:
          service:
            name: front
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:  
          service:
            name: app
            port:
              number: 80
