apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-back-ingress
  namespace: papello  # Specify the namespace here if needed
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Specify the Ingress class name
  rules:
  - http:
      paths:
      - path: /papello
        pathType: Prefix
        backend:
          service:
            name: front
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:  
          service:
            name: back
            port:
              number: 80
