apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
    tier: front
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: front
    tier: front