apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  selector: # postgresql Pod Should contain same labels
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: postgresql
        tier: database
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine3.18
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_USER
              value: devuser
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgresql-persistance-storage
      volumes:
        - name: postgresql-persistance-storage
          persistentVolumeClaim:
            claimName: postgresql-pv-claim-papello